[package]
name = "transcript"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
hound = "3.5.0"
whisper-rs = "0.8.0"
