on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: test-buiold
      TAGS: v1 ${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup and Build
        run: docker build .
